trigger:
- master

pool:
  name: 'SelfHostedAgents_ms'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dotnetSdkVersion: '8.0.x'  # Updated to match project's .NET 8.0 target

steps:
# Install .NET SDK with correct version
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetSdkVersion)'
    includePreviewVersions: false
    performMultiLevelLookup: true

# Install additional .NET workloads
- script: |
    dotnet workload install wasm-tools
  displayName: 'Install additional .NET workloads'
  continueOnError: true

# Verify SDK installation
- script: |
    dotnet --list-sdks
    dotnet --info
  displayName: 'Verify .NET SDK Installation'

# Use DotNetCoreCLI for restore
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

# Build with dotnet
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Test with dotnet
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'

# Publish web app
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
